#!/bin/bash

# Prepare a system so that converge escripts can be run on it.  To do this,
# install erlang + curl + ar, but get erlang from our custom-packages repository,
# so first install custom-packages-client and the spiped_key, along with the
# custom-packages apt key and a suitable apt/sources.list.

set -eu -o pipefail

SELF=$(dirname "${BASH_SOURCE[0]}")
CUSTOM_PACKAGES_CLIENT_DEB_PATH=$(/bin/ls -1 /var/custom-packages/custom-packages-client_*_all.deb | sort | tail -n 1)
CUSTOM_PACKAGES_APT_KEY_FILE=/var/custom-packages/keyFile
CUSTOM_PACKAGES_CLIENT_SPIPED_KEY_FILE=~/code/erlang/role_custom_packages_server/files/etc/custom-packages-server/spiped_key
CUSTOM_PACKAGES_PASSWORD=$(cat ~/code/erlang/role_custom_packages_server/files/etc/custom-packages-server/unencrypted_password)
USER_AT_HOST="$1"

ssh "$USER_AT_HOST" "mkdir -p ~/.machine_manager/bootstrap/ /etc/custom-packages-client/"
rsync "$CUSTOM_PACKAGES_CLIENT_SPIPED_KEY_FILE" "$USER_AT_HOST:/etc/custom-packages-client/spiped_key"
rsync "$CUSTOM_PACKAGES_CLIENT_DEB_PATH"        "$USER_AT_HOST:.machine_manager/bootstrap/custom-packages-client.deb"
rsync "$SELF/setup"                             "$USER_AT_HOST:.machine_manager/bootstrap/setup"
cat "$CUSTOM_PACKAGES_APT_KEY_FILE" | ssh "$USER_AT_HOST" "
	chattr -i /etc/apt/trusted.gpg &&
	apt-key add - &&
	chmod +x ~/.machine_manager/bootstrap/setup &&
	CUSTOM_PACKAGES_PASSWORD=$CUSTOM_PACKAGES_PASSWORD ~/.machine_manager/bootstrap/setup"
