#!/bin/bash

# Prepare a system so that converge escripts can be run on it.  To do this,
# install erlang + curl + ar, but get erlang from our custom-packages repository,
# so first install custom-packages-client and the spiped_key, along with the
# custom-packages apt key and a suitable apt/sources.list.

set -eu -o pipefail

CUSTOM_PACKAGES_CLIENT_DEB_PATH=$(/bin/ls -1 /var/custom-packages/custom-packages-client_*_all.deb | sort | tail -n 1)
CUSTOM_PACKAGES_APT_KEY_FILE=/var/custom-packages/keyFile
CUSTOM_PACKAGES_CLIENT_SPIPED_KEY_FILE=~/code/erlang/role_custom_packages_server/files/etc/custom-packages-server/spiped_key
CUSTOM_PACKAGES_PASSWORD=$(cat ~/code/erlang/role_custom_packages_server/files/etc/custom-packages-server/unencrypted_password)
USER_AT_HOST="$1"

ssh "$USER_AT_HOST" "mkdir -p ~/.machine_manager/bootstrap/ /etc/custom-packages-client/"
rsync "$CUSTOM_PACKAGES_CLIENT_SPIPED_KEY_FILE" "$USER_AT_HOST:/etc/custom-packages-client/spiped_key"
rsync "$CUSTOM_PACKAGES_CLIENT_DEB_PATH"        "$USER_AT_HOST:.machine_manager/bootstrap/custom-packages-client.deb"
cat "$CUSTOM_PACKAGES_APT_KEY_FILE" | ssh "$USER_AT_HOST" "chattr -i /etc/apt/trusted.gpg && apt-key add -"
ssh "$USER_AT_HOST" "
	# Stop and mask the service to prevent it from starting before we install
	# spiped_key with the correct owner
	echo Stopping service... && (systemctl stop custom-packages-client.service || true) &&
	systemctl mask custom-packages-client.service &&

	# Remove custom-packages apt source in case we are re-bootstrapping
	cat /etc/apt/sources.list | fgrep -v 'http://packages:' > /tmp/sources.list &&
	mv /tmp/sources.list /etc/apt/sources.list &&
	chmod a+r /etc/apt/sources.list &&

	# Install custom-packages-client
	apt-get update &&
	apt-get install -y --reinstall ~/.machine_manager/bootstrap/custom-packages-client.deb &&
	chown root:custom-packages-client /etc/custom-packages-client/spiped_key &&
	systemctl unmask custom-packages-client.service &&
	echo Stopping service... && (systemctl stop custom-packages-client.service || true) &&
	echo Starting service... && systemctl start custom-packages-client.service &&

	# Now actually install erlang
	chattr -i /etc/apt/sources.list &&
	sed -i '1s,^,deb [lang=\"none\"] http://packages:${CUSTOM_PACKAGES_PASSWORD}@127.0.0.1:28000/ .\/,' /etc/apt/sources.list &&
	apt-get update &&
	apt-get install -y --no-install-recommends --upgrade erlang-base-hipe erlang-crypto curl binutils
	"
