#!/bin/bash

# Make a machine_manager directory including the converge script for a
# particular machine.  Useful if you can't reach it over ssh, e.g. a new
# install being done in a chroot.

set -eu -o pipefail

hostname=$1
output=$2

EXTRA="$(dirname -- "$(realpath -- "$0")")"

mkdir -p -- "$output"
tags=$(mm get-tags "$hostname")
echo -E "$tags"                               > "$output"/tags
mm wireguard_config $hostname                 > "$output"/wg0.conf
mm hosts_json_file  $hostname                 > "$output"/hosts.json
mm script           $hostname                   "$output"/script
cp -a               $EXTRA/systemctl_for_chroot "$output"/systemctl
cp -a               $EXTRA/dig_for_chroot       "$output"/dig
mm portable_erlang  $hostname                   "$output/erlang"

echo '#!/bin/sh
SELF="$(dirname -- "$(realpath -- "$0")")"
cd "$SELF"
./erlang/bin/escript script $(cat tags)
' > "$output"/configure_normal
chmod +x "$output"/configure_normal

echo '#!/bin/sh
SELF="$(dirname -- "$(realpath -- "$0")")"
cd "$SELF"
PATH="$SELF:$PATH" ./erlang/bin/escript script $(cat tags)
' > "$output"/configure_chroot
chmod +x "$output"/configure_chroot
